export const DATA_SOURCES = [
  {
    id: "dlr-2022",
    title: "Tree Species Germany 2022",
    owner: "DLR Earth Observation Center",
    detail: "Dominant species at 10 m from Sentinel-1/2 + DEM. Ten groups including pine, spruce, beech, oak, birch, fir, Douglas fir, larch, alder.",
    year: "2022",
    license: "CC BY 4.0",
    doi: "10.15489/smh8w3j8i962",
    href: "https://geoservice.dlr.de/web/datasets/treespecies_de_2022",
    paper: "https://doi.org/10.1080/01431161.2025.2530236",
    access: "WMS layer TREE_SPECIES_DE_2022 · https://geoservice.dlr.de/eoc/land/wms",
    role: "Production raster (recommended)",
  },
  {
    id: "bwi-2022",
    title: "Bundeswaldinventur 2022",
    owner: "BMEL / Thünen Institute",
    detail: "National Forest Inventory area shares used for the Waldanteil bar (Kiefer 21.8%, Fichte 20.9%, Buche 16.6%, Eiche ~11.5%).",
    year: "2022",
    license: "GeoNutzV / official",
    doi: null,
    href: "https://www.bundeswaldinventur.de/",
    paper: "https://www.bmel.de/DE/themen/wald/wald-in-deutschland/bundeswaldinventur.html",
    access: "Result database at bwi.info",
    role: "Official shares",
  },
  {
    id: "thuenen-2018",
    title: "Dominant Tree Species Germany 2017/2018",
    owner: "Thünen Institute & HU Berlin",
    detail: "11 species groups trained on NFI plots with Sentinel-1/2. Overall accuracy ~75% including mixed stands, ~87% in pure stands.",
    year: "2017–2018",
    license: "CC BY 4.0",
    doi: "10.3220/DATA20221214084846",
    href: "https://doi.org/10.3220/DATA20221214084846",
    paper: "https://doi.org/10.1016/j.rse.2024.114069",
    access: "OpenAgrar GeoTIFF Dominant_Species_Class.tif",
    role: "NFI-calibrated alternative",
  },
] as const;
